export const GET_MESSAGES_START = 'GET_MESSAGES_START';
export const GET_MESSAGES_END = 'GET_MESSAGES_END';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';

export const POST_MESSAGE_START = 'POST_MESSAGE_START';
export const POST_MESSAGE_END = 'POST_MESSAGE_END';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const POST_MESSAGE_FAIL = 'POST_MESSAGE_FAIL';

export const GET_MESSAGE_START = 'GET_MESSAGE_START';
export const GET_MESSAGE_END = 'GET_MESSAGE_END';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAIL = 'GET_MESSAGE_FAIL';

export const UPDATE_MESSAGE_START = 'UPDATE_MESSAGE_START';
export const UPDATE_MESSAGE_END = 'UPDATE_MESSAGE_END';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_FAIL = 'UPDATE_MESSAGE_FAIL';
